/**
 * Generates supabase/seed.sql from the park layout in src/lib/park.ts.
 *
 *   npx tsx scripts/generate-seed.mts
 *
 * Benches are spaced evenly along each area's paths, alternating sides of the
 * path, so the map reads like benches lining a walkway. Install slots sit on
 * the Great Lawn's outer edge. Everything is deterministic; adoptions use
 * setseed() so their pseudo-random draws are reproducible too.
 */
import { writeFileSync } from "node:fs";
import { PARK, type XY } from "../src/lib/park";

const round1 = (n: number) => Math.round(n * 10) / 10;
const sqlStr = (s: string) => `'${s.replace(/'/g, "''")}'`;

/** Points spaced evenly along a set of polylines, offset ±d alternately. */
function alongPaths(paths: XY[][], count: number, offset: number): XY[] {
  const segs: { a: XY; b: XY; len: number }[] = [];
  for (const path of paths) {
    for (let i = 0; i < path.length - 1; i++) {
      const a = path[i], b = path[i + 1];
      segs.push({ a, b, len: Math.hypot(b[0] - a[0], b[1] - a[1]) });
    }
  }
  const total = segs.reduce((s, x) => s + x.len, 0);
  const step = total / count;
  const out: XY[] = [];
  let seg = 0, into = step / 2;
  for (let n = 0; n < count; n++) {
    while (into > segs[seg].len && seg < segs.length - 1) { into -= segs[seg].len; seg++; }
    const { a, b, len } = segs[seg];
    const t = Math.min(into / len, 1);
    const ux = (b[0] - a[0]) / len, uy = (b[1] - a[1]) / len;      // unit along
    const side = n % 2 === 0 ? 1 : -1;
    out.push([round1(a[0] + ux * len * t - uy * offset * side), round1(a[1] + uy * len * t + ux * offset * side)]);
    into += step;
  }
  return out;
}

const lines: string[] = [];
lines.push(`-- Bench Adoption Program — seed data
-- GENERATED by scripts/generate-seed.mts from src/lib/park.ts. Do not edit by hand.
--
-- ${PARK.name} is fictional. The brief simulates a park whose benches have
-- already been mapped, so every bench carries a position (park-local metres).
-- Shape of the data:
--   * ${PARK.areas.length} areas, ${PARK.areas.reduce((s, a) => s + a.benches, 0)} installed benches, spaced evenly along each area's paths.
--   * Bench ids are sequential inventory tags (RB-0001 ...).
--   * Style: every 3rd bench is concrete-base, the rest World's Fair.
--   * Size: every 4th bench is 4 ft (one side), the rest 8 ft (two sides).
--   * ${PARK.areas.find((a) => a.slots)?.slots ?? 0} pre-approved install slots on the Great Lawn edge (GL-SLOT-xx), installed = false; 3 taken.
--   * Each area has its own adoption rate (${Math.min(...PARK.areas.map((a) => a.adoptRate)) * 100}%–${Math.max(...PARK.areas.map((a) => a.adoptRate)) * 100}% of sides). Active adoptions are dated
--     0-12 years ago with a 10-year term, so those older than 10 years read as
--     'open' — the lazy-expiry path exercised by the seed itself.
--   * ~8% of sides also carry an older, already-expired adoption (history).
--
-- Re-runnable: wipes the three tables first.
truncate adoptions, benches, areas cascade;

select setseed(0.42);

insert into areas (id, name, description, sort_order) values`);
lines.push(PARK.areas.map((a, i) => `  (${sqlStr(a.id)}, ${sqlStr(a.name)}, ${sqlStr(a.description)}, ${i + 1})`).join(",\n") + ";");

lines.push(`\ninsert into benches (id, area_id, style, size_ft, installed, pos_x, pos_y) values`);
const rows: string[] = [];
let seq = 0;
for (const area of PARK.areas) {
  for (const [x, y] of alongPaths(area.paths, area.benches, 7)) {
    seq++;
    const id = `RB-${String(seq).padStart(4, "0")}`;
    const style = seq % 3 === 0 ? "concrete" : "worlds_fair";
    const size = seq % 4 === 0 ? 4 : 8;
    rows.push(`  (${sqlStr(id)}, ${sqlStr(area.id)}, ${sqlStr(style)}, ${size}, true, ${x}, ${y})`);
  }
}
for (const area of PARK.areas) {
  if (!area.slots) continue;
  // slots along the area's outer edge, just inside the boundary
  const loop = [...area.polygon, area.polygon[0]];
  alongPaths([loop], area.slots, -8).forEach(([x, y], i) => {
    rows.push(`  (${sqlStr(`GL-SLOT-${String(i + 1).padStart(2, "0")}`)}, ${sqlStr(area.id)}, 'worlds_fair', 8, false, ${x}, ${y})`);
  });
}
lines.push(rows.join(",\n") + ";");

const rateCase = PARK.areas.map((a) => `      when ${sqlStr(a.id)} then ${a.adoptRate.toFixed(2)}`).join("\n");
lines.push(`
-- Adoptions ------------------------------------------------------------------
-- One statement, no helper tables. Donor names and plaque templates are
-- picked per row by random array index, so random() is re-evaluated per side.
with
sides as (
  select
    b.id as bench_id,
    s.side,
    b.installed,
    case b.area_id
${rateCase}
      else 0.30
    end as adopt_rate,
    random() as r_active,
    random() as r_history,
    random() as r_age,
    (array['Maria Alvarez','James O''Connor','Priya Raman','Daniel Cohen','Aisha Bello',
           'Thomas Nguyen','Rosa Delgado','Samuel Kim','Elena Petrova','Marcus Johnson',
           'Hannah Weiss','Luis Ferreira','Grace Okafor','Noah Feldman','Yuki Tanaka',
           'Patrick Murphy','Fatima Hassan','Robert Callahan','Ingrid Larsen','Carlos Mendes'])
      [1 + floor(random() * 20)::int] as donor_a,
    (array['Maria Alvarez','James O''Connor','Priya Raman','Daniel Cohen','Aisha Bello',
           'Thomas Nguyen','Rosa Delgado','Samuel Kim','Elena Petrova','Marcus Johnson',
           'Hannah Weiss','Luis Ferreira','Grace Okafor','Noah Feldman','Yuki Tanaka',
           'Patrick Murphy','Fatima Hassan','Robert Callahan','Ingrid Larsen','Carlos Mendes'])
      [1 + floor(random() * 20)::int] as donor_b,
    (array[E'In loving memory of {name}\\nWho walked these paths every morning',
           E'For {name}\\nThis was your favorite spot\\nWe miss you',
           E'{name}\\n1948 – 2019\\nRest here a while',
           E'Dedicated to {name}\\nCoach, neighbor, friend\\nRiverbend Track Club',
           E'She said yes here.\\n{name}\\nJune 2021',
           E'For {name}\\nwho loved this park\\nand everyone in it',
           E'In honor of {name}\\n40 years of Saturday mornings\\non the Great Lawn'])
      [1 + floor(random() * 7)::int] as plaque_a,
    (array[E'In loving memory of {name}\\nWho walked these paths every morning',
           E'For {name}\\nThis was your favorite spot\\nWe miss you',
           E'{name}\\n1948 – 2019\\nRest here a while',
           E'Dedicated to {name}\\nCoach, neighbor, friend\\nRiverbend Track Club',
           E'For {name}\\nwho loved this park\\nand everyone in it'])
      [1 + floor(random() * 5)::int] as plaque_b
  from benches b
  cross join (values ('A'), ('B')) as s (side)
  where s.side = 'A' or b.size_ft = 8
)
insert into adoptions (bench_id, side, kind, donor_name, plaque_text, amount_usd, adopted_at, term_years, status)
-- older, already-expired adoptions (history) on ~8% of sides
select bench_id, side, 'adopt', donor_b, replace(plaque_b, '{name}', donor_b), 2500,
       now() - interval '14 years' - (r_age * interval '6 years'), 10, 'expired'
from sides where installed and r_history < 0.08
union all
-- current adoptions at the area's rate, dated 0-12 years ago (some already lapsed)
select bench_id, side, 'adopt', donor_a, replace(plaque_a, '{name}', donor_a), 3500,
       now() - (r_age * interval '12 years'), 10, 'active'
from sides where installed and r_active < adopt_rate
union all
-- three install slots already taken (side A only until installed)
select bench_id, side, 'install_and_adopt', donor_a, replace(plaque_a, '{name}', donor_a), 5500,
       now() - (r_age * interval '2 years'), 10, 'active'
from sides where not installed and side = 'A' and bench_id in ('GL-SLOT-02', 'GL-SLOT-05', 'GL-SLOT-09');
`);

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), lines.join("\n"));
console.log(`wrote supabase/seed.sql: ${seq} benches`);
